extends Node
#var rutaArchivos =  OS.get_executable_path().get_base_dir()   #RUTA DE ARCHIVOS PARA JUEGO PORTABLE EN WINDOWS O SISTEMA DE PC
var rutaArchivos =  "user://"  #RUTA DE ARCHIVOS PARA ANDROID, SISTEMAS OPERATIVOS DE CELULAR O PARA EL JUEGO NO PORTABLE COMO HTML
